"""initial schema

Revision ID: d263a44e8ad2
Revises: 
Create Date: 2026-07-21 15:46:36.312327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd263a44e8ad2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('is_senior', sa.Boolean(), nullable=False),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', 'SENIOR', 'TEACHER', 'SCHOOL', name='subscription_tier_enum'), nullable=False),
    sa.Column('oauth_provider', sa.Enum('APPLE', 'GOOGLE', 'WECHAT', 'LOCAL', name='oauth_provider_enum'), nullable=False),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=False)
    op.create_index(op.f('ix_users_subscription_tier'), 'users', ['subscription_tier'], unique=False)
    op.create_table('curriculum_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day_num', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.String(length=50), nullable=False),
    sa.Column('block_type', sa.Enum('WARMUP_PITCH', 'HAND', 'EXPRESSIVENESS', 'SIGHT_READING', 'MAIN_PIECE', 'REVIEW', 'WEAKNESS', 'COOLDOWN', name='block_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day_num', 'block_id', name='uq_user_day_block')
    )
    op.create_index(op.f('ix_curriculum_progress_block_type'), 'curriculum_progress', ['block_type'], unique=False)
    op.create_index(op.f('ix_curriculum_progress_created_at'), 'curriculum_progress', ['created_at'], unique=False)
    op.create_index(op.f('ix_curriculum_progress_user_id'), 'curriculum_progress', ['user_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('piece_name', sa.String(length=255), nullable=False),
    sa.Column('piece_composer', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'ELEMENTARY', 'INTERMEDIATE', 'ADVANCED', name='difficulty_enum'), nullable=False),
    sa.Column('midi_url', sa.String(length=1024), nullable=False),
    sa.Column('midi_size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('pitch_score', sa.Float(), nullable=False),
    sa.Column('expressiveness_score', sa.Float(), nullable=False),
    sa.Column('hand_pose_score', sa.Float(), nullable=False),
    sa.Column('rhythm_score', sa.Float(), nullable=False),
    sa.Column('sight_reading_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('llm_feedback', sa.String(length=8192), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('llm_latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_created_at'), 'evaluations', ['created_at'], unique=False)
    op.create_index(op.f('ix_evaluations_overall_score'), 'evaluations', ['overall_score'], unique=False)
    op.create_index(op.f('ix_evaluations_piece_name'), 'evaluations', ['piece_name'], unique=False)
    op.create_index(op.f('ix_evaluations_user_id'), 'evaluations', ['user_id'], unique=False)
    op.create_table('sight_reading_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'ELEMENTARY', 'INTERMEDIATE', 'ADVANCED', name='sight_reading_difficulty_enum'), nullable=False),
    sa.Column('mode', sa.Enum('RANDOM', 'INTERVAL', 'PIECE', name='sight_reading_mode_enum'), nullable=False),
    sa.Column('input_method', sa.Enum('KEYBOARD', 'MIDI', 'NOTE_NAME', name='sight_reading_input_enum'), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('streak_max', sa.Integer(), nullable=False),
    sa.Column('notes_per_minute', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sight_reading_sessions_created_at'), 'sight_reading_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sight_reading_sessions_difficulty'), 'sight_reading_sessions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_sight_reading_sessions_started_at'), 'sight_reading_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_sight_reading_sessions_user_id'), 'sight_reading_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sight_reading_sessions_user_id'), table_name='sight_reading_sessions')
    op.drop_index(op.f('ix_sight_reading_sessions_started_at'), table_name='sight_reading_sessions')
    op.drop_index(op.f('ix_sight_reading_sessions_difficulty'), table_name='sight_reading_sessions')
    op.drop_index(op.f('ix_sight_reading_sessions_created_at'), table_name='sight_reading_sessions')
    op.drop_table('sight_reading_sessions')
    op.drop_index(op.f('ix_evaluations_user_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_piece_name'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_overall_score'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_created_at'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_curriculum_progress_user_id'), table_name='curriculum_progress')
    op.drop_index(op.f('ix_curriculum_progress_created_at'), table_name='curriculum_progress')
    op.drop_index(op.f('ix_curriculum_progress_block_type'), table_name='curriculum_progress')
    op.drop_table('curriculum_progress')
    op.drop_index(op.f('ix_users_subscription_tier'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
